// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-bMY0fyMC9XX3QZl_2z4AtjNSphf8pxE',
    appId: '1:932668103377:web:37af04c0d79ebfb6f7c3f0',
    messagingSenderId: '932668103377',
    projectId: 'spreadit-b8b53',
    authDomain: 'spreadit-b8b53.firebaseapp.com',
    storageBucket: 'spreadit-b8b53.appspot.com',
    measurementId: 'G-14L5Y6VJ0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMX5Ew7oZKA2Ao4OxsdcyIkJ1LzBxCufo',
    appId: '1:932668103377:android:0c499dc4690dc13ff7c3f0',
    messagingSenderId: '932668103377',
    projectId: 'spreadit-b8b53',
    storageBucket: 'spreadit-b8b53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANA8YGUMNICV9A89cxXs8R1M-H4_hj8A0',
    appId: '1:546473234311:ios:ff8ce01e89aebed4cb4d22',
    messagingSenderId: '546473234311',
    projectId: 'spreadit-5a997',
    storageBucket: 'spreadit-5a997.appspot.com',
    iosClientId:
        '546473234311-511m13erocmi67d2qvmrf29hk924qkpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.spreaditCrossplatform',
  );
}